# Generated by Django 4.1.7 on 2023-02-25 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(max_length=30, unique=True, verbose_name="cессия"),
                ),
            ],
            options={"verbose_name": "владелец", "verbose_name_plural": "владельцы",},
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_url", models.URLField(verbose_name="ссылка")),
                (
                    "subpart",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="суб домен"
                    ),
                ),
                (
                    "request_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="количество переходов"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shorter.owner",
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={"verbose_name": "токен", "verbose_name_plural": "токены",},
        ),
    ]
